spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/commushop?characterEncoding=utf8&serverTimezone=GMT%2b8
      username: root
      password: 123456
  application:
    name: commushop_dev
server:
  port: 8080
  servlet:
     context-path: /api

