spring:
  datasource:
    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver #mysql的驱动类
#      url: jdbc:mysql://localhost:3306/commushop?characterEncoding=utf8&serverTimezone=GMT%2b8 #mysql的地址
#      username: root #mysql的账号
#      password: 123456 #mysql的密码

      driver-class-name: com.mysql.cj.jdbc.Driver #mysql的驱动类
      url: jdbc:mysql://8.137.53.253:3306/commushopdev?characterEncoding=utf8&serverTimezone=GMT%2b8 #mysql的地址
      username: root #mysql的账号
      password: mysql_hercyz #mysql的密码
  application:
    name: commushop_dev #项目名称
  servlet:
    multipart:
      enabled: true #是否启用文件上传
      location: ./temp/upload #文件上传的临时路径
      max-file-size: 10MB #文件上传的最大大小
      max-request-size: 10MB #请求的最大大小
  redis:
    host: 8.137.53.253
    port: 6379
    password: redis_FcaJWr
    timeout: 5000
server:
  port: 8081 #服务端口
  servlet:
     context-path: /api #接口路径
minio:
  endpoint: http://8.137.53.253:9000 #minio的地址
  accessKey: BE83o8xLiyLLiq70dDzl #minio的访问密钥
  secretKey: rj2OEb1zUiU360OLXhcn6ZfnB19UgZXdvdvg7Nr0 #minio的访问密钥
  bucketName: commoshop #minio的存储桶名称

jwt:
  secret: commushop-jwt-secret-key-must-be-at-least-32-bytes
  expiration: 86400000  # 24 hours in milliseconds
  tokenPrefix: "Bearer "
  headerKey: "Authorization"
deepseek:
  api:
    url: https://api.deepseek.com/chat/completions
    key: sk-56085f2f63e14c949d20afc8846551b3
coze:
  api:
    url: https://api.coze.cn/open_api/v2/chat
    key: pat_RMD84xdLyyniJKBiyHTz7JOM45GwPJL8UwpXcFbw294bC2f62zqE2wSBIO8oQ6SP
  bot:
    id: 7485968377924747318
chat:
  service:
    type: coze
